services:



    liquetsoft_fias.informer.soap:
        class: SoapClient
        arguments:
            - '%liquetsoft_fias.informer_wsdl%'
            - {exceptions: true}

    liquetsoft_fias.informer.service:
        class: Liquetsoft\Fias\Component\FiasInformer\SoapFiasInformer
        arguments:
            - '@liquetsoft_fias.informer.soap'

    Liquetsoft\Fias\Component\FiasInformer\FiasInformer:
        alias: liquetsoft_fias.informer.service



    liquetsoft_fias.downloader.service:
        class: Liquetsoft\Fias\Component\Downloader\CurlDownloader

    Liquetsoft\Fias\Component\Downloader\Downloader:
        alias: liquetsoft_fias.downloader.service



    liquetsoft_fias.unpacker.service:
        class: Liquetsoft\Fias\Component\Unpacker\RarUnpacker

    Liquetsoft\Fias\Component\Unpacker\Unpacker:
        alias: liquetsoft_fias.unpacker.service



    liquetsoft_fias.xml_reader.service:
        class: Liquetsoft\Fias\Component\XmlReader\BaseXmlReader

    Liquetsoft\Fias\Component\XmlReader\XmlReader:
        alias: liquetsoft_fias.xml_reader.service



    liquetsoft_fias.serializer.serializer:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Serializer\FiasSerializer



    liquetsoft_fias.entity_registry.service:
        class: Liquetsoft\Fias\Component\EntityRegistry\YamlEntityRegistry
        arguments:
            - '%liquetsoft_fias.registry_yaml%'

    Liquetsoft\Fias\Component\EntityRegistry\EntityRegistry:
        alias: liquetsoft_fias.entity_registry.service



    liquetsoft_fias.entity_manager.service:
        class: Liquetsoft\Fias\Component\EntityManager\BaseEntityManager
        arguments:
            - '@liquetsoft_fias.entity_registry.service'
            - '%liquetsoft_fias.entity_bindings%'

    Liquetsoft\Fias\Component\EntityManager\EntityManager:
        alias: liquetsoft_fias.entity_manager.service



    liquetsoft_fias.storage.service:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Storage\DoctrineStorage
        arguments:
            - '@doctrine'
            - '%liquetsoft_fias.insert_batch_count%'

    Liquetsoft\Fias\Component\Storage\Storage:
        alias: liquetsoft_fias.storage.service



    liquetsoft_fias.task.cleanup:
        class: Liquetsoft\Fias\Component\Pipeline\Task\CleanupTask

    liquetsoft_fias.task.prepare.folder:
        class: Liquetsoft\Fias\Component\Pipeline\Task\PrepareFolderTask
        arguments:
            - '%liquetsoft_fias.temp_dir%'

    liquetsoft_fias.task.inform.full:
        class: Liquetsoft\Fias\Component\Pipeline\Task\InformFullTask
        arguments:
            - '@liquetsoft_fias.informer.service'

    liquetsoft_fias.task.download:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DownloadTask
        arguments:
            - '@liquetsoft_fias.downloader.service'

    liquetsoft_fias.task.unpack:
        class: Liquetsoft\Fias\Component\Pipeline\Task\UnpackTask
        arguments:
            - '@liquetsoft_fias.unpacker.service'

    liquetsoft_fias.task.truncate:
        class: Liquetsoft\Fias\Component\Pipeline\Task\TruncateTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.storage.service'

    liquetsoft_fias.task.data.insert:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DataInsertTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.xml_reader.service'
            - '@liquetsoft_fias.storage.service'
            - '@liquetsoft_fias.serializer.serializer'

    liquetsoft_fias.task.data.delete:
        class: Liquetsoft\Fias\Component\Pipeline\Task\DataDeleteTask
        arguments:
            - '@liquetsoft_fias.entity_manager.service'
            - '@liquetsoft_fias.xml_reader.service'
            - '@liquetsoft_fias.storage.service'
            - '@liquetsoft_fias.serializer.serializer'



    liquetsoft_fias.pipe.install:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.prepare.folder'
                - '@liquetsoft_fias.task.inform.full'
                - '@liquetsoft_fias.task.download'
                - '@liquetsoft_fias.task.unpack'
                - '@liquetsoft_fias.task.truncate'
                - '@liquetsoft_fias.task.data.insert'
                - '@liquetsoft_fias.task.data.delete'
            $cleanupTask: '@liquetsoft_fias.task.cleanup'

    liquetsoft_fias.pipe.install_from_folder:
        class: Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe
        arguments:
            $tasks:
                - '@liquetsoft_fias.task.truncate'
                - '@liquetsoft_fias.task.data.insert'
                - '@liquetsoft_fias.task.data.delete'



    liquetsoft_fias.command.install:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\InstallCommand
        arguments:
            - '@liquetsoft_fias.pipe.install'
        tags:
            - { name: 'console.command' }

    liquetsoft_fias.command.install_from_file:
        class: Liquetsoft\Fias\Symfony\LiquetsoftFiasBundle\Command\InstallFromFolderCommand
        arguments:
            - '@liquetsoft_fias.pipe.install_from_folder'
        tags:
            - { name: 'console.command' }
